"""Skills subsystem: reusable instructions injected into agent prompts.

A skill is a folder with a ``SKILL.md`` (frontmatter + Markdown instructions).
The file on disk is always the source of truth, so a skill can be hand-written,
generated by an LLM through conversation, copied from a colleague, or committed to
a project's git repo - and all four behave identically afterwards.

Public surface::

    from papercreator.skills import loader, runner

    loader.list_with_status(project_id=...)     # for the UI
    loader.save_skill(name=..., instructions=...)
    loader.sync_registry()                      # filesystem -> db
    runner.render_for_prompt(ids, role="writer")
    await runner.draft_skill_with_llm("make it write like a Nature paper")

Scopes: ``builtin`` (shipped, read-only), ``user`` (``<home>/skills``),
``project`` (``<project>/.papercreator/skills``, travels with git). Later scopes
override earlier ones by id.

See ``docs/systems/skill_system.md``.
"""

from . import loader, runner  # noqa: F401
from .model import Skill, parse_skill_text, render_skill_file  # noqa: F401

__all__ = [
    "Skill",
    "loader",
    "parse_skill_text",
    "render_skill_file",
    "runner",
]
