/**
 * Skills view: list, edit, and author skills - by hand or by asking the model.
 *
 * LLM authoring is two-step on purpose: the model proposes, the user reviews and
 * saves. A skill silently changes every future prompt, so it should not appear
 * without being read once.
 */

import { useEffect, useState } from "react";

import * as endpoints from "../api/endpoints";
import { useStore } from "../state/store";
import type { SkillDraft, SkillInfo } from "../api/types";

export function SkillsView() {
  const skills = useStore((s) => s.skills);
  const loadSkills = useStore((s) => s.loadSkills);
  const enabledSkills = useStore((s) => s.enabledSkillIds);
  const locale = useStore((s) => s.locale);
  const notify = useStore((s) => s.notify);
  const hasLlm = useStore((s) => s.health?.llm.has_any ?? false);

  const [editing, setEditing] = useState<SkillInfo | "new" | null>(null);
  const [drafting, setDrafting] = useState(false);
  const [directories, setDirectories] = useState<Record<string, string>>({});
  const [validRoles, setValidRoles] = useState<string[]>([]);
  const [preview, setPreview] = useState<Record<string, any> | null>(null);

  useEffect(() => {
    void endpoints.skills
      .list()
      .then((result) => {
        setDirectories(result.directories);
        setValidRoles(result.valid_roles);
      })
      .catch(() => undefined);
  }, []);

  return (
    <div className="view">
      <div className="row">
        <div className="grow">
          <h1>{locale === "zh-CN" ? "技能" : "Skills"}</h1>
          <p className="sub">
            {locale === "zh-CN"
              ? "技能是注入到 agent system prompt 的固定指令，用来固化写作规范。每个技能就是一个含 SKILL.md 的文件夹，可以手写、让 AI 生成，或从别人那里复制。"
              : "A skill is a set of standing instructions injected into the agents' system prompt. Each one is a folder with a SKILL.md — hand-written, generated by the model, or copied from someone else."}
          </p>
        </div>
        <button className="btn" onClick={() => setEditing("new")}>
          {locale === "zh-CN" ? "手写技能" : "Write one"}
        </button>
        <button
          className="btn primary"
          onClick={() => setDrafting(true)}
          disabled={!hasLlm}
          title={hasLlm ? undefined : locale === "zh-CN" ? "需要先配置 LLM 提供方" : "Needs an LLM provider"}
        >
          {locale === "zh-CN" ? "让 AI 生成" : "Ask the AI"}
        </button>
      </div>

      {drafting && <DraftModal onClose={() => setDrafting(false)} onSaved={() => void loadSkills()} />}
      {editing && (
        <EditModal
          skill={editing === "new" ? null : editing}
          validRoles={validRoles}
          onClose={() => setEditing(null)}
          onSaved={() => void loadSkills()}
        />
      )}

      <div className="card">
        <div className="row">
          <span className="dim grow">
            {locale === "zh-CN" ? "已启用的技能会在下一次 agent 运行时生效。" : "Enabled skills apply to the next agent run."}
            {"  "}
            {enabledSkills.length}/{skills.length}{" "}
            {locale === "zh-CN" ? "启用" : "enabled"}
          </span>
          <button
            className="btn sm"
            onClick={async () => {
              const result = await endpoints.skills.preview(enabledSkills, "writer");
              setPreview(result);
            }}
          >
            {locale === "zh-CN" ? "预览注入内容" : "Preview what gets injected"}
          </button>
          <button
            className="btn sm"
            onClick={async () => {
              const result = await endpoints.skills.sync();
              notify({
                kind: "success",
                message: locale === "zh-CN" ? `发现 ${result.count} 个技能` : `${result.count} skills found`,
                detail: locale === "zh-CN" ? `清理 ${result.pruned} 条过期索引` : `pruned ${result.pruned} stale entries`,
              });
              void loadSkills();
            }}
            title={
              locale === "zh-CN"
                ? "重新扫描技能目录，拾取手工编辑或 git pull 的改动"
                : "Rescan the skill directories, picking up hand edits and git pulls"
            }
          >
            {locale === "zh-CN" ? "重新扫描" : "Rescan"}
          </button>
        </div>
        {directories.user && (
          <div className="dim mono" style={{ fontSize: "var(--fs-xs)", marginTop: 6 }}>
            {locale === "zh-CN" ? "用户技能目录：" : "user skills: "}
            {directories.user}
            <button
              className="btn sm"
              style={{ marginLeft: 8 }}
              onClick={() => void window.papercreator?.shell.openPath(directories.user)}
            >
              {locale === "zh-CN" ? "打开目录" : "open folder"}
            </button>
          </div>
        )}
      </div>

      {preview && (
        <div className="card">
          <div className="row">
            <h3 className="grow" style={{ margin: 0 }}>
              {locale === "zh-CN" ? "注入到 system prompt 的内容" : "Injected into the system prompt"}
            </h3>
            <span className="chip">
              {preview.estimated_tokens} / {preview.budget_tokens} tok
            </span>
            <button className="btn icon sm" onClick={() => setPreview(null)} aria-label={locale === "zh-CN" ? "关闭提示词预览" : "Close prompt preview"}>
              ✕
            </button>
          </div>
          {(preview.problems as string[]).map((problem, index) => (
            <p key={index} className="warn-text" style={{ fontSize: "var(--fs-sm)" }}>
              ⚠ {problem}
            </p>
          ))}
          <pre
            className="mono"
            style={{
              whiteSpace: "pre-wrap",
              background: "var(--bg-app)",
              padding: 10,
              maxHeight: 320,
              overflow: "auto",
            }}
          >
            {String(preview.text) || "(nothing — no skills enabled for this role)"}
          </pre>
        </div>
      )}

      <div className="cards">
        {skills.map((skill) => (
          <SkillCard
            key={skill.id}
            skill={skill}
            enabled={enabledSkills.includes(skill.id)}
            onEdit={() => setEditing(skill)}
            onChanged={() => void loadSkills()}
          />
        ))}
      </div>
    </div>
  );
}

function SkillCard({
  skill,
  enabled,
  onEdit,
  onChanged,
}: {
  skill: SkillInfo;
  enabled: boolean;
  onEdit: () => void;
  onChanged: () => void;
}) {
  const toggleSkill = useStore((s) => s.toggleSkill);
  const locale = useStore((s) => s.locale);
  const notify = useStore((s) => s.notify);
  const reportError = useStore((s) => s.reportError);

  return (
    <div className="card" style={{ borderColor: enabled ? "var(--focus)" : undefined }}>
      <div className="row">
        <label className="row grow" style={{ gap: 7 }}>
          <input type="checkbox" checked={enabled} onChange={() => toggleSkill(skill.id)} />
          <span style={{ fontWeight: 600 }}>{skill.name}</span>
        </label>
        <span className={`chip ${skill.scope === "builtin" ? "" : "ok"}`}>{skill.scope}</span>
      </div>
      <p className="muted" style={{ fontSize: "var(--fs-sm)", minHeight: 34 }}>
        {skill.description}
      </p>
      <div className="row wrap" style={{ gap: 4 }}>
        {skill.applies_to.map((role) => (
          <span key={role} className="chip">
            {role}
          </span>
        ))}
        {skill.origin === "llm" && <span className="chip warn">{locale === "zh-CN" ? "AI 生成" : "AI-authored"}</span>}
        {skill.usage_count > 0 && (
          <span className="chip" title="How many times this skill has been injected">
            {locale === "zh-CN" ? "已使用" : "used"} {skill.usage_count}×
          </span>
        )}
        <span className="chip dim" title="Prompt cost">
          {Math.ceil(skill.instruction_chars / 4)} tok
        </span>
      </div>
      {skill.checksum_matches === false && (
        <p className="warn-text" style={{ fontSize: "var(--fs-xs)", marginTop: 6 }}>
          {locale === "zh-CN"
            ? "磁盘上的文件已被修改（重新扫描以更新缓存）"
            : "The file on disk changed — rescan to refresh the cache"}
        </p>
      )}
      <div className="row" style={{ marginTop: 10 }}>
        {skill.editable ? (
          <button className="btn sm" onClick={onEdit}>
            {locale === "zh-CN" ? "编辑" : "Edit"}
          </button>
        ) : (
          <button
            className="btn sm"
            title={
              locale === "zh-CN"
                ? "内置技能只读。复制为用户技能后即可编辑（同名会覆盖内置）。"
                : "Builtins are read-only. Copy it to your own skills to edit; the same id overrides the builtin."
            }
            onClick={async () => {
              try {
                await endpoints.skills.copy(skill.id);
                notify({ kind: "success", message: locale === "zh-CN" ? "已复制到你的技能" : "Copied to your skills" });
                onChanged();
              } catch (error) {
                reportError(error, "copying the skill");
              }
            }}
          >
            {locale === "zh-CN" ? "复制以编辑" : "Copy to edit"}
          </button>
        )}
        <button
          className="btn sm"
          onClick={async () => {
            await endpoints.skills.setEnabled(skill.id, !skill.enabled);
            onChanged();
          }}
          title={
            locale === "zh-CN"
              ? "永久禁用（重新扫描后仍然保持）"
              : "Disable persistently — survives a rescan"
          }
        >
          {skill.enabled
            ? locale === "zh-CN" ? "停用" : "Disable"
            : locale === "zh-CN" ? "恢复" : "Re-enable"}
        </button>
        {skill.editable && (
          <button
            className="btn sm danger"
            onClick={async () => {
              if (!window.confirm(locale === "zh-CN" ? `删除技能“${skill.name}”及其文件夹？` : `Delete the skill "${skill.name}" and its folder?`)) return;
              try {
                await endpoints.skills.remove(skill.id);
                notify({ kind: "success", message: locale === "zh-CN" ? "已删除" : "Deleted" });
                onChanged();
              } catch (error) {
                reportError(error, "deleting the skill");
              }
            }}
          >
            {locale === "zh-CN" ? "删除" : "Delete"}
          </button>
        )}
      </div>
    </div>
  );
}

function DraftModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const locale = useStore((s) => s.locale);
  const notify = useStore((s) => s.notify);
  const reportError = useStore((s) => s.reportError);
  const [request, setRequest] = useState("");
  const [draft, setDraft] = useState<SkillDraft | null>(null);
  const [busy, setBusy] = useState(false);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(event) => event.stopPropagation()}>
        <header>
          <span>{locale === "zh-CN" ? "让 AI 写一个技能" : "Have the model write a skill"}</span>
          <button className="btn icon sm" onClick={onClose} aria-label={locale === "zh-CN" ? "关闭技能草稿" : "Close skill draft"}>
            ✕
          </button>
        </header>
        <div className="modal-body">
          <div className="field">
            <label>{locale === "zh-CN" ? "你想要什么样的写作规范？" : "What writing convention do you want?"}</label>
            <textarea
              rows={4}
              autoFocus
              value={request}
              onChange={(event) => setRequest(event.target.value)}
              placeholder={
                locale === "zh-CN"
                  ? "例如：按 Nature 的风格写作，摘要不分段，避免使用第一人称，方法细节放到补充材料。"
                  : "e.g. Write in Nature's style: unstructured abstract, no first person, method detail moved to supplementary."
              }
            />
          </div>
          <button
            className="btn primary"
            disabled={busy || !request.trim()}
            onClick={async () => {
              setBusy(true);
              try {
                const result = await endpoints.skills.draft(request);
                setDraft(result.draft);
              } catch (error) {
                reportError(error, "drafting the skill");
              } finally {
                setBusy(false);
              }
            }}
          >
            {busy ? (locale === "zh-CN" ? "生成中…" : "Drafting…") : locale === "zh-CN" ? "生成草稿" : "Draft it"}
          </button>

          {draft && (
            <>
              <h3 style={{ marginTop: 18 }}>{draft.name}</h3>
              <p className="muted">{draft.description}</p>
              <div className="row wrap" style={{ gap: 5, marginBottom: 10 }}>
                {draft.applies_to.map((role) => (
                  <span key={role} className="chip on">
                    {role}
                  </span>
                ))}
                {draft.triggers.map((trigger) => (
                  <span key={trigger} className="chip">
                    ⌕ {trigger}
                  </span>
                ))}
                <span className="chip">{draft.estimated_prompt_tokens} tok</span>
              </div>
              {draft.warnings.map((warning, index) => (
                <p key={index} className="warn-text" style={{ fontSize: "var(--fs-sm)" }}>
                  ⚠ {warning}
                </p>
              ))}
              <div className="field">
                <label>{locale === "zh-CN" ? "指令内容（可直接修改）" : "Instructions (editable)"}</label>
                <textarea
                  rows={12}
                  value={draft.instructions}
                  onChange={(event) => setDraft({ ...draft, instructions: event.target.value })}
                />
              </div>
              {draft.rationale && (
                <p className="dim" style={{ fontSize: "var(--fs-sm)" }}>
                  {locale === "zh-CN" ? "模型的理由：" : "The model's rationale: "}
                  {draft.rationale}
                </p>
              )}
            </>
          )}
        </div>
        {draft && (
          <footer>
            <button className="btn" onClick={onClose}>
              {locale === "zh-CN" ? "放弃" : "Discard"}
            </button>
            <button
              className="btn primary"
              onClick={async () => {
                try {
                  await endpoints.skills.save({ ...draft, scope: "user", overwrite: true });
                  notify({ kind: "success", message: locale === "zh-CN" ? `已保存技能“${draft.name}”` : `Saved skill "${draft.name}"` });
                  onSaved();
                  onClose();
                } catch (error) {
                  reportError(error, "saving the skill");
                }
              }}
            >
              {locale === "zh-CN" ? "保存技能" : "Save skill"}
            </button>
          </footer>
        )}
      </div>
    </div>
  );
}

function EditModal({
  skill,
  validRoles,
  onClose,
  onSaved,
}: {
  skill: SkillInfo | null;
  validRoles: string[];
  onClose: () => void;
  onSaved: () => void;
}) {
  const locale = useStore((s) => s.locale);
  const notify = useStore((s) => s.notify);
  const reportError = useStore((s) => s.reportError);
  const [form, setForm] = useState({
    id: skill?.id ?? "",
    name: skill?.name ?? "",
    description: skill?.description ?? "",
    instructions: "",
    applies_to: skill?.applies_to ?? ["all"],
    triggers: (skill?.triggers ?? []).join(", "),
    tags: (skill?.tags ?? []).join(", "),
    priority: skill?.priority ?? 50,
  });
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!skill) return;
    void endpoints.skills
      .get(skill.id)
      .then((result) => setForm((current) => ({ ...current, instructions: String(result.instructions ?? "") })))
      .catch(() => undefined);
  }, [skill]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(event) => event.stopPropagation()}>
        <header>
          <span>
            {skill
              ? locale === "zh-CN" ? "编辑技能" : "Edit skill"
              : locale === "zh-CN" ? "新建技能" : "New skill"}
          </span>
          <button className="btn icon sm" onClick={onClose} aria-label={locale === "zh-CN" ? "关闭技能编辑" : "Close skill editor"}>
            ✕
          </button>
        </header>
        <div className="modal-body">
          <div className="row">
            <div className="field grow">
              <label>{locale === "zh-CN" ? "名称" : "Name"}</label>
              <input
                autoFocus
                value={form.name}
                onChange={(event) => setForm({ ...form, name: event.target.value })}
              />
            </div>
            <div className="field" style={{ width: 110 }}>
              <label title="Lower renders first in the prompt">
                {locale === "zh-CN" ? "优先级" : "Priority"}
              </label>
              <input
                type="number"
                value={form.priority}
                onChange={(event) => setForm({ ...form, priority: Number(event.target.value) || 50 })}
              />
            </div>
          </div>
          <div className="field">
            <label>{locale === "zh-CN" ? "一句话说明" : "One-line description"}</label>
            <input
              value={form.description}
              onChange={(event) => setForm({ ...form, description: event.target.value })}
            />
          </div>
          <div className="field">
            <label>{locale === "zh-CN" ? "适用角色" : "Applies to"}</label>
            <div className="row wrap" style={{ gap: 5 }}>
              {validRoles.map((role) => (
                <button
                  key={role}
                  className={`chip clickable${form.applies_to.includes(role) ? " on" : ""}`}
                  onClick={() =>
                    setForm({
                      ...form,
                      applies_to: form.applies_to.includes(role)
                        ? form.applies_to.filter((entry) => entry !== role)
                        : [...form.applies_to.filter((entry) => entry !== "all"), role],
                    })
                  }
                >
                  {role}
                </button>
              ))}
            </div>
          </div>
          <div className="field">
            <label>
              {locale === "zh-CN" ? "触发词（逗号分隔）" : "Triggers (comma separated)"}
            </label>
            <input
              value={form.triggers}
              onChange={(event) => setForm({ ...form, triggers: event.target.value })}
              placeholder="IEEE, conference paper, survey"
            />
            <span className="hint">
              {locale === "zh-CN"
                ? "用于根据项目内容自动建议启用哪些技能。"
                : "Used to suggest this skill based on the project's own text."}
            </span>
          </div>
          <div className="field">
            <label>{locale === "zh-CN" ? "指令内容（Markdown）" : "Instructions (Markdown)"}</label>
            <textarea
              rows={16}
              value={form.instructions}
              onChange={(event) => setForm({ ...form, instructions: event.target.value })}
              placeholder={
                locale === "zh-CN"
                  ? "用命令式写清楚要求，例如「使用英式拼写」「首次出现的缩写必须展开」。"
                  : "Imperative and checkable: 'Use British spelling.' 'Expand every acronym at first use.'"
              }
            />
            <span className="hint">
              {locale === "zh-CN"
                ? `约 ${Math.ceil(form.instructions.length / 4)} tokens。过长会挤占提示词中留给文献的空间。`
                : `~${Math.ceil(form.instructions.length / 4)} tokens. Too long crowds out the literature in the prompt.`}
            </span>
          </div>
        </div>
        <footer>
          <button className="btn" onClick={onClose}>
            {locale === "zh-CN" ? "取消" : "Cancel"}
          </button>
          <button
            className="btn primary"
            disabled={busy || !form.name.trim() || !form.instructions.trim()}
            onClick={async () => {
              setBusy(true);
              try {
                await endpoints.skills.save({
                  ...form,
                  triggers: form.triggers.split(",").map((s) => s.trim()).filter(Boolean),
                  tags: form.tags.split(",").map((s) => s.trim()).filter(Boolean),
                  scope: "user",
                  overwrite: true,
                });
                notify({ kind: "success", message: locale === "zh-CN" ? "已保存" : "Saved" });
                onSaved();
                onClose();
              } catch (error) {
                reportError(error, locale === "zh-CN" ? "保存技能" : "saving the skill");
              } finally {
                setBusy(false);
              }
            }}
          >
            {locale === "zh-CN" ? "保存" : "Save"}
          </button>
        </footer>
      </div>
    </div>
  );
}
