"""Building a complete, compilable LaTeX project.

Produces the directory an Overleaf project or a local ``latexmk`` run expects::

    main.tex          document with preamble, body, bibliography
    references.bib    generated from the cited papers
    sections/*.tex    one file per section, \\input from main.tex
    figures/          copied from the project's assets

Section files are separate and ``\\input``-ed rather than inlined, because that is
how a real LaTeX project is organised: it keeps diffs small, lets co-authors work
on different sections, and matches what Overleaf users expect.

Engine choice matters for Chinese: pdflatex cannot typeset CJK, so a manuscript
detected as Chinese gets a xelatex preamble with ``ctex``. Choosing the wrong
engine produces a build failure that is confusing to debug, so it is decided from
the content rather than left to the user.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import Any

from ..core.logging_setup import get_logger
from ..core.models import Paper, ProjectModel
from ..core.util import detect_language, safe_filename
from ..writing import citations as citations_module
from .markdown_latex import escape_latex, markdown_to_latex

log = get_logger(__name__)

# Document classes offered in the export dialog. `options` are appended to
# \documentclass; `requires` lists packages the class does not pull in itself.
DOCUMENT_CLASSES: dict[str, dict[str, Any]] = {
    "article": {
        "name": "Article (generic)",
        "class": "article",
        "options": "11pt,a4paper",
        "two_column": False,
    },
    "ieee": {
        "name": "IEEE conference (IEEEtran)",
        "class": "IEEEtran",
        "options": "conference",
        "two_column": True,
        "note": "needs IEEEtran.cls - bundled with TeX Live and available on "
                "Overleaf",
    },
    "acm": {
        "name": "ACM (acmart)",
        "class": "acmart",
        "options": "sigconf",
        "two_column": True,
        "note": "needs acmart.cls",
    },
    "llncs": {
        "name": "Springer LNCS",
        "class": "llncs",
        "options": "",
        "two_column": False,
        "note": "needs llncs.cls",
    },
    "report": {
        "name": "Report / thesis chapter",
        "class": "report",
        "options": "12pt,a4paper",
        "two_column": False,
    },
}

_COMMON_PACKAGES = [
    ("inputenc", "utf8", "pdflatex only"),
    ("fontenc", "T1", "pdflatex only"),
    ("graphicx", "", ""),
    ("amsmath", "", ""),
    ("amssymb", "", ""),
    ("booktabs", "", ""),
    ("hyperref", "hidelinks", ""),
    ("url", "", ""),
    ("cite", "", "ieee only"),
]

_CITE_COMMAND = re.compile(r"\\cite\{[a-z0-9,]+\}")


def _markdown_with_citations(
    text: str,
    keys: citations_module.CitationKeyMap,
    *,
    unicode_safe: bool,
) -> tuple[str, list[str]]:
    """Convert Markdown while preserving generated ``\\cite`` commands.

    Citation rewriting must happen before Markdown conversion so ordinary
    bracketed prose and unknown markers remain auditable.  The converter quite
    correctly escapes raw backslashes, however, so generated citation commands
    are replaced with private-use placeholders for that pass and restored only
    afterwards.  Without this boundary a valid ``[KEY]`` became the literal text
    ``\\textbackslash{}cite\\{key\\}`` in exported LaTeX.
    """

    rewritten, unknown = citations_module.to_latex_citations(text, keys)
    commands: list[str] = []

    def protect(match: re.Match[str]) -> str:
        commands.append(match.group(0))
        return f"\ue000PCCITE{len(commands) - 1}\ue001"

    protected = _CITE_COMMAND.sub(protect, rewritten)
    converted = markdown_to_latex(protected, unicode_safe=unicode_safe)
    for index, command in enumerate(commands):
        converted = converted.replace(f"\ue000PCCITE{index}\ue001", command)
    return converted, unknown


def build_preamble(
    *,
    document_class: str = "article",
    engine: str = "pdflatex",
    language: str = "en",
    title: str = "",
    authors: list[str] | None = None,
    bibliography_style: str = "IEEEtran",
) -> str:
    """Assemble the preamble for the chosen class, engine and language."""
    spec = DOCUMENT_CLASSES.get(document_class) or DOCUMENT_CLASSES["article"]
    is_cjk = language == "zh"
    lines: list[str] = [
        "% Generated by PaperCreator. Safe to edit; regenerating overwrites it.",
        f"% Engine: {engine}   Class: {spec['class']}   Language: {language}",
        "",
    ]

    if is_cjk:
        # ctex must load before most packages and requires xelatex.
        lines.append(f"\\documentclass[{spec['options']}]{{{spec['class']}}}"
                     if spec["options"] else
                     f"\\documentclass{{{spec['class']}}}")
        lines.append("\\usepackage[UTF8]{ctex}   % Chinese support; needs xelatex")
    else:
        lines.append(f"\\documentclass[{spec['options']}]{{{spec['class']}}}"
                     if spec["options"] else
                     f"\\documentclass{{{spec['class']}}}")

    for package, options, restriction in _COMMON_PACKAGES:
        if package in ("inputenc", "fontenc") and (engine != "pdflatex" or is_cjk):
            # Both are unnecessary and can conflict under xelatex/lualatex.
            continue
        if restriction == "ieee only" and document_class != "ieee":
            continue
        lines.append(
            f"\\usepackage[{options}]{{{package}}}" if options
            else f"\\usepackage{{{package}}}"
        )

    lines.append("")
    if title:
        lines.append(f"\\title{{{escape_latex(title, unicode_safe=is_cjk)}}}")
    if authors:
        joined = " \\and ".join(
            escape_latex(a, unicode_safe=is_cjk) for a in authors
        )
        lines.append(f"\\author{{{joined}}}")
    else:
        lines.append("\\author{}")
    lines.append("")
    return "\n".join(lines)


def build_main_tex(
    *,
    preamble: str,
    abstract: str,
    section_files: list[str],
    bibliography_style: str = "IEEEtran",
    bib_name: str = "references",
    include_toc: bool = False,
) -> str:
    """The ``main.tex`` that ties the project together."""
    lines = [preamble, "\\begin{document}", "\\maketitle", ""]
    if abstract.strip():
        lines.extend(["\\begin{abstract}", abstract.strip(), "\\end{abstract}", ""])
    if include_toc:
        lines.extend(["\\tableofcontents", "\\clearpage", ""])
    for name in section_files:
        lines.append(f"\\input{{sections/{name}}}")
    lines.extend([
        "",
        f"\\bibliographystyle{{{bibliography_style}}}",
        f"\\bibliography{{{bib_name}}}",
        "",
        "\\end{document}",
        "",
    ])
    return "\n".join(lines)


def export_latex_project(
    *,
    project: ProjectModel,
    blocks: list[dict[str, Any]],
    papers: list[Paper],
    keys: citations_module.CitationKeyMap,
    target_dir: Path,
    document_class: str = "article",
    engine: str = "",
    language: str = "primary",
    bibliography_style: str = "",
    include_toc: bool = False,
    assets_dir: Path | None = None,
) -> dict[str, Any]:
    """Write a complete LaTeX project. Returns a report for the UI.

    ``blocks`` come from :func:`writing.manuscript.assemble`, so the abstract is
    detected by key rather than by position - a manuscript without an abstract
    section must still export.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    sections_dir = target_dir / "sections"
    sections_dir.mkdir(exist_ok=True)

    body_text = "\n".join(block["text"] for block in blocks)
    detected = detect_language(body_text)
    is_cjk = detected == "zh"
    resolved_engine = engine or ("xelatex" if is_cjk else "pdflatex")
    if is_cjk and resolved_engine == "pdflatex":
        # Silently producing an unbuildable project would be worse than
        # overriding a wrong choice, so override and report it.
        resolved_engine = "xelatex"
        log.info("switched engine to xelatex: the manuscript contains CJK text")

    resolved_bib_style = bibliography_style or {
        "ieee": "IEEEtran", "acm": "ACM-Reference-Format", "llncs": "splncs04",
    }.get(document_class, "plain")

    # 1. Section files, with citation markers rewritten to \cite.
    section_files: list[str] = []
    abstract_text = ""
    unknown_keys: set[str] = set()
    for block in blocks:
        converted, unknown = _markdown_with_citations(
            block["text"], keys, unicode_safe=is_cjk
        )
        unknown_keys.update(unknown)
        if block["key"] in ("abstract", "摘要"):
            # The abstract belongs in \begin{abstract}, not as a section.
            abstract_text = converted
            continue
        name = safe_filename(block["key"])
        heading_command = {
            1: "section", 2: "subsection", 3: "subsubsection",
        }.get(block["level"], "section")
        title = escape_latex(block["title"], unicode_safe=is_cjk)
        (sections_dir / f"{name}.tex").write_text(
            f"\\{heading_command}{{{title}}}\n\\label{{sec:{name}}}\n\n{converted}",
            encoding="utf-8",
        )
        section_files.append(name)

    # 2. Bibliography from the cited papers only.
    cited = citations_module.cited_papers(
        [b["text"] for b in blocks], keys, {p.id: p for p in papers}
    )
    bib_text = citations_module.build_bibtex(cited or papers, keys)
    (target_dir / "references.bib").write_text(bib_text, encoding="utf-8")

    # 3. main.tex
    preamble = build_preamble(
        document_class=document_class,
        engine=resolved_engine,
        language="zh" if is_cjk else "en",
        title=project.title_zh if is_cjk and project.title_zh else project.title,
        authors=[],
        bibliography_style=resolved_bib_style,
    )
    (target_dir / "main.tex").write_text(
        build_main_tex(
            preamble=preamble,
            abstract=abstract_text,
            section_files=section_files,
            bibliography_style=resolved_bib_style,
            include_toc=include_toc,
        ),
        encoding="utf-8",
    )

    # 4. Figures.
    copied_assets = 0
    if assets_dir and assets_dir.is_dir():
        figures_dir = target_dir / "figures"
        figures_dir.mkdir(exist_ok=True)
        for asset in assets_dir.rglob("*"):
            if asset.is_file() and asset.suffix.lower() in (
                ".png", ".jpg", ".jpeg", ".pdf", ".eps", ".svg"
            ):
                shutil.copy2(asset, figures_dir / asset.name)
                copied_assets += 1

    # 5. A build script, so the user does not have to remember the bibtex dance.
    (target_dir / "build.sh").write_text(
        "#!/bin/sh\n"
        "# Two latex passes around bibtex are required to resolve citations.\n"
        f"{resolved_engine} main\n"
        "bibtex main\n"
        f"{resolved_engine} main\n"
        f"{resolved_engine} main\n",
        encoding="utf-8",
    )
    (target_dir / "build.bat").write_text(
        "@echo off\r\n"
        "REM Two latex passes around bibtex are required to resolve citations.\r\n"
        f"{resolved_engine} main\r\n"
        "bibtex main\r\n"
        f"{resolved_engine} main\r\n"
        f"{resolved_engine} main\r\n",
        encoding="utf-8",
    )

    report = {
        "path": str(target_dir),
        "main": str(target_dir / "main.tex"),
        "engine": resolved_engine,
        "document_class": document_class,
        "bibliography_style": resolved_bib_style,
        "sections": section_files,
        "has_abstract": bool(abstract_text),
        "bib_entries": len(cited or papers),
        "assets_copied": copied_assets,
        "language": "zh" if is_cjk else "en",
        "warnings": [],
    }
    if unknown_keys:
        report["warnings"].append(
            f"{len(unknown_keys)} citation marker(s) had no matching paper and were "
            f"left as plain text: {', '.join(sorted(unknown_keys)[:10])}"
        )
    if is_cjk:
        report["warnings"].append(
            "Chinese text detected: compile with xelatex (the generated build "
            "scripts already do). pdflatex cannot typeset CJK."
        )
    spec = DOCUMENT_CLASSES.get(document_class) or {}
    if spec.get("note"):
        report["warnings"].append(spec["note"])
    log.info(
        "exported LaTeX project to %s (%s sections, %s bib entries, %s)",
        target_dir, len(section_files), report["bib_entries"], resolved_engine,
    )
    return report


def describe_classes() -> list[dict[str, Any]]:
    return [
        {"id": key, **{k: v for k, v in value.items() if k != "class"},
         "latex_class": value["class"]}
        for key, value in DOCUMENT_CLASSES.items()
    ]
