"""Project repository.

A project is two things kept in sync:

* a row in ``projects`` (metadata, settings, id),
* a directory under the workspace containing the actual manuscript, its
  bibliography, exports and a git repo.

This module owns both. The directory layout it creates is::

    <workspace>/<slug>/
        project.json          human-readable mirror of the DB row (survives a
                              lost database - see import_from_disk)
        manuscript/           section markdown/latex files, git-tracked
        references/           references.bib, notes per paper
        assets/               figures, tables, images
        exports/              generated .tex/.docx/.md bundles (regenerable)
        analysis/             exported landscape JSON snapshots
        .papercreator/        project-local cache; gitignored

Deletion never removes the directory unless the caller explicitly asks, and
even then only the workspace subtree is touched.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from ..core.db import dumps, execute, loads, query, query_one, transaction
from ..core.errors import ConflictError, NotFoundError, ValidationError
from ..core.logging_setup import get_logger
from ..core.models import ProjectModel
from ..core.paths import get_paths
from ..core.util import new_id, slugify, utc_now_iso
from . import papers as papers_store

log = get_logger(__name__)

PROJECT_SUBDIRS = (
    "manuscript", "references", "assets", "exports", "analysis", ".papercreator"
)

_PROJECT_GITIGNORE = """# PaperCreator project
.papercreator/
exports/
*.aux
*.log
*.out
*.bbl
*.blg
*.synctex.gz
*.fdb_latexmk
*.fls
*.toc
"""


def _row_to_project(row: Any) -> ProjectModel:
    data = dict(row)
    return ProjectModel(
        id=data["id"],
        slug=data.get("slug") or "",
        title=data.get("title") or "",
        title_zh=data.get("title_zh") or "",
        description=data.get("description") or "",
        idea=data.get("idea") or "",
        research_field=data.get("research_field") or "",
        target_venue=data.get("target_venue") or "",
        template_id=data.get("template_id") or "generic",
        language=data.get("language") or "en",
        bilingual=bool(data.get("bilingual", 1)),
        citation_style=data.get("citation_style") or "ieee",
        path=data.get("path") or "",
        git_enabled=bool(data.get("git_enabled", 1)),
        status=data.get("status") or "active",
        settings=loads(data.get("settings"), {}) or {},
        created_at=data.get("created_at") or "",
        updated_at=data.get("updated_at") or "",
    )


def unique_slug(title: str, *, exclude_id: str = "") -> str:
    """Slug that collides with neither an existing row nor an existing directory.

    Both checks matter: a leftover directory from a deleted project would
    otherwise be silently adopted (and its files mixed with the new project).
    """
    base = slugify(title, fallback="paper")
    workspace = get_paths().workspace
    candidate = base
    suffix = 2
    while True:
        row = query_one(
            "SELECT id FROM projects WHERE slug=? AND id != ?", (candidate, exclude_id)
        )
        if row is None and not (workspace / candidate).exists():
            return candidate
        candidate = f"{base}-{suffix}"
        suffix += 1


def project_root(project: ProjectModel) -> Path:
    """Resolved directory for a project, honouring a relocated ``path``."""
    if project.path:
        return Path(project.path)
    return get_paths().project_dir(project.slug)


def scaffold_directory(root: Path) -> None:
    """Create the on-disk skeleton. Idempotent; never overwrites content."""
    root.mkdir(parents=True, exist_ok=True)
    for name in PROJECT_SUBDIRS:
        (root / name).mkdir(parents=True, exist_ok=True)
    gitignore = root / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_PROJECT_GITIGNORE, encoding="utf-8")
    bib = root / "references" / "references.bib"
    if not bib.exists():
        bib.write_text(
            "% Generated by PaperCreator. Regenerate from the library at any\n"
            "% time; manual edits here are overwritten on export.\n",
            encoding="utf-8",
        )


def write_project_json(project: ProjectModel) -> None:
    """Mirror the DB row into ``project.json`` for disaster recovery.

    The database is the source of truth at runtime; this file is what
    :func:`import_from_disk` reads when the database is lost or the workspace
    is moved to another machine.
    """
    root = project_root(project)
    root.mkdir(parents=True, exist_ok=True)
    payload = project.model_dump(
        exclude={"paper_count", "word_count", "section_count"}
    )
    (root / "project.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def create(
    *,
    title: str,
    title_zh: str = "",
    description: str = "",
    idea: str = "",
    research_field: str = "",
    target_venue: str = "",
    template_id: str = "generic",
    language: str = "en",
    bilingual: bool = True,
    citation_style: str = "ieee",
    slug: str = "",
    git_enabled: bool = True,
) -> ProjectModel:
    """Create the row, the directory and the default collection."""
    if not title.strip():
        raise ValidationError("project title is required")
    resolved_slug = slug.strip() or unique_slug(title)
    if query_one("SELECT id FROM projects WHERE slug=?", (resolved_slug,)):
        raise ConflictError(f"project slug '{resolved_slug}' already exists")

    pid = new_id("prj")
    root = get_paths().project_dir(resolved_slug)
    now = utc_now_iso()
    with transaction():
        execute(
            "INSERT INTO projects (id, slug, title, title_zh, description, idea,"
            " research_field, target_venue, template_id, language, bilingual,"
            " citation_style, path, git_enabled, status, settings, created_at,"
            " updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,'active','{}',?,?)",
            (pid, resolved_slug, title.strip(), title_zh.strip(), description,
             idea, research_field, target_venue, template_id, language,
             int(bilingual), citation_style, str(root), int(git_enabled), now, now),
        )
        papers_store.ensure_collection(pid, papers_store.DEFAULT_COLLECTION)
    scaffold_directory(root)
    project = require(pid)
    write_project_json(project)
    log.info("created project %s (%s) at %s", title, pid, root)
    return project


def get(project_id: str) -> ProjectModel | None:
    row = query_one("SELECT * FROM projects WHERE id=?", (project_id,))
    return _row_to_project(row) if row else None


def get_by_slug(slug: str) -> ProjectModel | None:
    row = query_one("SELECT * FROM projects WHERE slug=?", (slug,))
    return _row_to_project(row) if row else None


def require(project_id: str) -> ProjectModel:
    project = get(project_id)
    if project is None:
        raise NotFoundError(f"project {project_id} not found")
    return project


def _augment_counts(project: ProjectModel) -> ProjectModel:
    """Fill the denormalised counters used by the project list UI."""
    project.paper_count = papers_store.project_paper_count(project.id)
    row = query_one(
        "SELECT COUNT(s.id) AS sections, COALESCE(SUM(s.word_count),0) AS words"
        " FROM sections s JOIN documents d ON d.id = s.document_id"
        " WHERE d.project_id=?",
        (project.id,),
    )
    if row:
        project.section_count = int(row["sections"] or 0)
        project.word_count = int(row["words"] or 0)
    return project


def list_projects(*, status: str = "", with_counts: bool = True) -> list[ProjectModel]:
    if status:
        rows = query(
            "SELECT * FROM projects WHERE status=? ORDER BY updated_at DESC", (status,)
        )
    else:
        rows = query("SELECT * FROM projects ORDER BY updated_at DESC")
    projects = [_row_to_project(r) for r in rows]
    return [_augment_counts(p) for p in projects] if with_counts else projects


def update(project_id: str, **fields: Any) -> ProjectModel:
    """Patch metadata. Renaming the title does *not* rename the directory.

    Directory renames would break git remotes, open editors and absolute paths
    stored elsewhere; :func:`relocate` exists for the rare deliberate move.
    """
    project = require(project_id)
    allowed = {
        "title", "title_zh", "description", "idea", "research_field",
        "target_venue", "template_id", "language", "citation_style", "status",
    }
    assignments, params = [], {}
    for key, value in fields.items():
        if key in allowed:
            assignments.append(f"{key}=:{key}")
            params[key] = value
        elif key in ("bilingual", "git_enabled"):
            assignments.append(f"{key}=:{key}")
            params[key] = int(bool(value))
        elif key == "settings":
            assignments.append("settings=:settings")
            params["settings"] = dumps(value)
    if not assignments:
        return _augment_counts(project)
    params["id"] = project_id
    params["updated_at"] = utc_now_iso()
    execute(
        f"UPDATE projects SET {','.join(assignments)}, updated_at=:updated_at"
        " WHERE id=:id",
        params,
    )
    updated = require(project_id)
    write_project_json(updated)
    return _augment_counts(updated)


def touch(project_id: str) -> None:
    """Bump ``updated_at`` so the project list orders by recent activity."""
    execute(
        "UPDATE projects SET updated_at=? WHERE id=?", (utc_now_iso(), project_id)
    )


def delete(project_id: str, *, remove_files: bool = False) -> dict[str, Any]:
    """Delete the row (cascades to collections/documents/analyses/runs).

    ``remove_files`` is opt-in and guarded: the directory must sit inside the
    configured workspace, otherwise a relocated project could delete an
    arbitrary path. Papers themselves stay in the global library.
    """
    project = require(project_id)
    root = project_root(project)
    removed_dir = False
    if remove_files:
        workspace = get_paths().workspace.resolve()
        try:
            inside = root.resolve().is_relative_to(workspace)
        except (OSError, ValueError):
            inside = False
        if not inside:
            raise ConflictError(
                f"refusing to delete '{root}': outside the workspace "
                f"'{workspace}'. Remove it manually if that is intended."
            )
        if root.exists():
            shutil.rmtree(root, ignore_errors=True)
            removed_dir = True
    execute("DELETE FROM projects WHERE id=?", (project_id,))
    log.info("deleted project %s (files removed: %s)", project_id, removed_dir)
    return {"deleted": True, "files_removed": removed_dir, "path": str(root)}


def relocate(project_id: str, new_path: str) -> ProjectModel:
    """Point the project at an existing directory (moved workspace, restore)."""
    project = require(project_id)
    target = Path(new_path).expanduser().resolve()
    if not target.is_dir():
        raise ValidationError(f"'{target}' is not an existing directory")
    execute(
        "UPDATE projects SET path=?, updated_at=? WHERE id=?",
        (str(target), utc_now_iso(), project_id),
    )
    scaffold_directory(target)
    updated = require(project_id)
    write_project_json(updated)
    log.info("relocated project %s: %s -> %s", project_id, project.path, target)
    return updated


def discover_on_disk() -> list[dict[str, Any]]:
    """Workspace directories holding a ``project.json`` with no DB row.

    Surfaced in the UI as "importable projects" after a database loss or when
    the workspace is copied from another machine.
    """
    workspace = get_paths().workspace
    if not workspace.is_dir():
        return []
    found: list[dict[str, Any]] = []
    for entry in sorted(workspace.iterdir()):
        if not entry.is_dir():
            continue
        manifest = entry / "project.json"
        if not manifest.is_file():
            continue
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            found.append({"path": str(entry), "slug": entry.name,
                          "error": f"unreadable project.json: {exc}"})
            continue
        pid = str(data.get("id") or "")
        if pid and query_one("SELECT id FROM projects WHERE id=?", (pid,)):
            continue
        if query_one("SELECT id FROM projects WHERE slug=?", (entry.name,)):
            continue
        found.append({
            "path": str(entry),
            "slug": entry.name,
            "id": pid,
            "title": data.get("title") or entry.name,
            "updated_at": data.get("updated_at") or "",
        })
    return found


def import_from_disk(path: str) -> ProjectModel:
    """Recreate a project row from a workspace directory's ``project.json``.

    Manuscript files are re-indexed by ``store.documents.reindex_from_disk``,
    which the caller (API route) invokes after this returns. Paper links cannot
    be recovered - they live only in the database.
    """
    root = Path(path).expanduser().resolve()
    manifest = root / "project.json"
    if not manifest.is_file():
        raise ValidationError(f"no project.json in '{root}'")
    data = json.loads(manifest.read_text(encoding="utf-8"))
    pid = str(data.get("id") or new_id("prj"))
    if query_one("SELECT id FROM projects WHERE id=?", (pid,)):
        raise ConflictError(f"project {pid} already exists in the database")
    slug = str(data.get("slug") or root.name)
    if query_one("SELECT id FROM projects WHERE slug=?", (slug,)):
        slug = unique_slug(slug)
    now = utc_now_iso()
    with transaction():
        execute(
            "INSERT INTO projects (id, slug, title, title_zh, description, idea,"
            " research_field, target_venue, template_id, language, bilingual,"
            " citation_style, path, git_enabled, status, settings, created_at,"
            " updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (pid, slug, data.get("title") or slug, data.get("title_zh") or "",
             data.get("description") or "", data.get("idea") or "",
             data.get("research_field") or "", data.get("target_venue") or "",
             data.get("template_id") or "generic", data.get("language") or "en",
             int(bool(data.get("bilingual", True))),
             data.get("citation_style") or "ieee", str(root),
             int(bool(data.get("git_enabled", True))),
             data.get("status") or "active", dumps(data.get("settings") or {}),
             data.get("created_at") or now, now),
        )
        papers_store.ensure_collection(pid, papers_store.DEFAULT_COLLECTION)
    scaffold_directory(root)
    log.info("imported project %s from %s", pid, root)
    return require(pid)
